### PR TITLE
upgrade to Neo 3.6.0 and .NET 7.0

### PR DESCRIPTION
**Pull request by Hecate2**
Still requires https://github.com/neoburger/TEE/pull/49 to work

### CODE REVIEW

**Comment by vang1ong7ang** [comment]
let's wait for mainnet upgrade

**Review by vang1ong7ang — APPROVED** [review]

**Comment by vang1ong7ang** [comment]
is it okay to merge? @Hecate2 @dusmart

**Comment by Hecate2** [comment]
> is it okay to merge? @Hecate2 @dusmart 

Not really safe to merge, though the codes work on my machine. I believe that the github action workflow files need changes as well. e.g.         dotnet-version: 6.0.x -> 7.0.x. The actions needs to be tested.

**Comment by vang1ong7ang** [comment]
@Hecate2 

ah yes, try to update the `dotnet-version` in those workflow yamls as well

**Review by vang1ong7ang — CHANGES_REQUESTED** [review]
yaml files as well

**Comment by Hecate2** [comment]
Tested in recent actions of https://github.com/Hecate2/TEE/actions
Had a hard time figuring out `secrets.CONFIG_MAINNET`. I compressed the whole mainnet config json string (of Neo 3.6.0), and packed the whole json in a pair of single quotes '' to make things work.

**Review by vang1ong7ang — APPROVED** [review]

**Pull request merged**
